const { HttpError } = require('../utils/httpError');
const AGGREGATES=new Set(['daily','weekly','monthly','yearly']);
function date(value,name){const s=String(value||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s+'T00:00:00Z')))throw new HttpError(400,'VALIDATION_ERROR',`${name} is invalid.`);return s;}
function range(q){const start=date(q.start,'Start date'),end=date(q.end,'End date');if(start>end)throw new HttpError(400,'VALIDATION_ERROR','Start date must be on or before end date.');return{start,end};}
function aggregate(q){const a=String(q.aggregate||'').toLowerCase();if(!AGGREGATES.has(a))throw new HttpError(400,'VALIDATION_ERROR','Aggregate must be daily, weekly, monthly, or yearly.');return a;}
function periodLabel(row,a){if(a==='daily')return row.periodStart;if(a==='weekly')return `${row.periodStart} - ${row.periodEnd}`;return row.periodKey;}
function totals(rows,fields){return Object.fromEntries(fields.map(f=>[f,rows.reduce((n,r)=>n+(Number(r[f])||0),0)]));}
function createReportService(repo){return{
 sales(q){const r=range(q),a=aggregate(q),rows=repo.sales(r.start,r.end,a).map(x=>({...x,dateRange:periodLabel(x,a)}));return{type:'Sales',aggregate:a,...r,rows,totals:totals(rows,['totalInvoices','totalQuantitySold','grossSalesCentavos','totalDiscountsCentavos','netSalesCentavos'])};},
 profit(q){const r=range(q),a=aggregate(q),rows=repo.profit(r.start,r.end,a).map(x=>({...x,dateRange:periodLabel(x,a)}));return{type:'Profit',aggregate:a,...r,rows,totals:totals(rows,['totalInvoices','totalQuantitySold','totalCostCentavos','grossSalesCentavos','totalDiscountsCentavos','grossProfitCentavos'])};},
 deliveries(q){const r=range(q),rows=repo.deliveries(r.start,r.end);return{type:'Deliveries',...r,rows,totals:totals(rows,['totalQuantity','totalCostCentavos'])};},
 itemPerformance(q){const r=range(q),rows=repo.itemPerformance(r.start,r.end);return{type:'Item Performance',...r,rows,totals:totals(rows,['totalQuantitySold','grossSalesCentavos','totalDiscountsCentavos','netSalesCentavos'])};},
 stockCard(q){const r=range(q),a=aggregate(q);let rows=repo.stockCard(r.start,r.end);if(a!=='daily'){const grouped=new Map();for(const x of rows){const d=new Date(x.movementDate+'T00:00:00Z');let key;if(a==='monthly')key=x.movementDate.slice(0,7);else if(a==='yearly')key=x.movementDate.slice(0,4);else{const t=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const day=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-day);const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));key=`${t.getUTCFullYear()}-W${String(Math.ceil((((t-y)/86400000)+1)/7)).padStart(2,'0')}`;}const k=[x.itemId,key,x.movementType].join('|');const old=grouped.get(k)||{...x,movementDate:key,quantity:0};old.quantity+=x.quantity;grouped.set(k,old);}rows=[...grouped.values()];}return{type:'Stock Card',aggregate:a,...r,rows};},
 itemAging(){const inv=repo.inventory(),by=new Map(inv.map(x=>[x.itemId,{...x,aged1to30:0,aged31to60:0,aged61to90:0,aged91Plus:0,untracked:0}]));for(const d of repo.agingDeliveries()){const x=by.get(d.itemId);if(!x)continue;if(d.ageDays<=30)x.aged1to30+=d.quantity;else if(d.ageDays<=60)x.aged31to60+=d.quantity;else if(d.ageDays<=90)x.aged61to90+=d.quantity;else x.aged91Plus+=d.quantity;}const rows=[];for(const x of by.values()){let tracked=x.aged1to30+x.aged31to60+x.aged61to90+x.aged91Plus;let excess=Math.max(0,tracked-x.quantity);for(const f of ['aged91Plus','aged61to90','aged31to60','aged1to30']){const take=Math.min(x[f],excess);x[f]-=take;excess-=take;}tracked=x.aged1to30+x.aged31to60+x.aged61to90+x.aged91Plus;x.untracked=Math.max(0,x.quantity-tracked);const weighted=x.aged1to30*15+x.aged31to60*45+x.aged61to90*75+x.aged91Plus*105;x.avgAge=tracked?Math.round(weighted*100/tracked)/100:0;if(x.quantity||tracked)rows.push(x);}rows.sort((a,b)=>b.avgAge-a.avgAge);return{type:'Item Aging',rows};},
 optimalOrders(){const rows=repo.optimalOrders().map(x=>{const weekly=x.days>0?x.qty/x.days*7:0;const safety=weekly*.15;const wos=weekly>0?x.currentStock/weekly:0;return{itemId:x.itemId,itemName:x.itemName,avgWeeklyDemand:Math.round(weekly*100)/100,wos:Math.round(wos*100)/100,safetyStock:Math.round(safety*100)/100,currentStock:x.currentStock,optimalOrderQuantity:Math.max(0,Math.round(weekly+weekly*.2-x.currentStock))};}).sort((a,b)=>b.optimalOrderQuantity-a.optimalOrderQuantity);return{rows};},
 records(){return{sales:repo.saleRecords(),deliveries:repo.deliveryRecords()};}
};}
module.exports={createReportService};
